### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/export/apple_health_export'apple-health-grafana-ingester-1 exited

### ISSUE THREAD

**Issue by GeraldPape** [k0rventen/apple-health-grafana#15]
after specifying the export.zip relative as proposed it fails with this error:

```
apple-health-grafana-ingester-1  | Unzipping the export file...
apple-health-grafana-ingester-1  | Export file unzipped!
apple-health-grafana-ingester-1  | Influx is ready.
apple-health-grafana-ingester-1  | No workout routes found, skipping ...
apple-health-grafana-ingester-1  | Traceback (most recent call last):
apple-health-grafana-ingester-1  |   File "//app.py", line 186, in <module>
apple-health-grafana-ingester-1  |     process_health_data(client)
apple-health-grafana-ingester-1  |   File "//app.py", line 131, in process_health_data
apple-health-grafana-ingester-1  |     export_xml_files = [f for f in os.listdir(EXPORT_PATH) if EXPORT_XML_REGEX.match(f)]
apple-health-grafana-ingester-1  |                                    ^^^^^^^^^^^^^^^^^^^^^^^
apple-health-grafana-ingester-1  | FileNotFoundError: [Errno 2] No such file or directory: '/export/apple_health_export'apple-health-grafana-ingester-1 exited with code 1
```

but ./export/apple_health_export/ exists,...

**Comment by k0rventen** [comment]
Hi, 
could you please paste the content of the `docker-compose.yml` file,  as well as the content of the directory in which you run `compose up` ? 

Thx

**Comment by GeraldPape** [comment]
docker-compose.yml
```
version: "3"
services:
  grafana:
    image: grafana/grafana:9.5.5
    ports:
    - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=health
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/dashs/specific-metrics.json
    volumes:
    - ./provisioning:/etc/grafana/provisioning
  influx:
    image: influxdb:1.8
    restart: always
    environment:
      - INFLUXDB_DB=health
    volumes:
    - influx-data:/var/lib/influxdb
  ingester:
    image: k0rventen/apple-health-grafana-ingester
    build: ./ingester
    volumes:
    - C:/temp/ap/apple-health-grafana/export.zip:/export.zip

volumes:
  influx-data:
```

and this is in the directory:
```
.github
.gitignore
docker-compose.ok
docker-compose.yml
docker-compose.yml.bak
example1.png
example2.png
export.zip
ingester
provisioning
README.md
tests
```
